module IPDSimulation
  POPULATION_SIZE = 25
  NUM_BITS = 23
  NUM_GENERATIONS = 1000
  CROSSOVER_RATE = 0.0
  MUTATION_RATE = 0.001

  # Game
  NR_ROUNDS = 10

  # Payoff MATRIX
  CC_SCORE = 4
  CD_SCORE = 0
  DC_SCORE = 6
  DD_SCORE = 2
end
